### ISSUE TITLE
String is a list in python

### ISSUE THREAD

**Issue by rukshn** [sahanruwantha/siconv#21]
String is a list in Python by default, therefore this casting is not necessary 

https://github.com/sahanruwantha/siconv/blob/7390e35b750e4f8c46af0bca982b2fce1cf19168/siconv/to_singlish.py#L24

**Comment by sahanruwantha** [comment]
I originally imported pillam and characters from another file, but i could import characters(dic) but not pillam(list).
for some reason it converts to unicord characters. so converting it to a list how i fixed. since now there is only file i suppose i could remove the type casting

**Comment by sahanruwantha** [comment]
I originally imported pillam and characters from another file, but i could import characters(dic) but not pillam(list).
for some reason it converts to unicord characters. so converting it to a list how i fixed. since now there is only file i suppose i could remove the type casting
